### ISSUE TITLE
Submodules & references to other submodules

### ISSUE THREAD

**Issue by emarcotte** [hach-que/Protobuild#86] opened 2015-01-25 15:46 UTC
I have a monogame project with an executable and a library. I then made MonoGame and the library submodules my executable's repository. I have set up a submodule for the library. Both the executable and the library depend on MonoGame so I added references to it in both places.

When I generate the solutions and attempt to compile, the library cannot find MonoGame.

    /opt/mono/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MonoGame.Framework' not resolved
    /opt/mono/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MonoGame.Framework.Net' not resolved

If I move the MonoGame submodule inside the library project things work fine for both the library and the executable project.

Should submodules be able to resolve dependencies from the project they're included from? If not, what is the proper way to set up this type of project?

**Comment by hach-que** [comment] 2015-02-03 21:35
Modules don't resolve dependencies above or across the hierarchy; they can only see projects defined inside them or inside their submodules.  In this case, the library can't see MonoGame because it resides above it in the hierarchy.

The reason for this is that a flat hierarchy tends to lead to dependency hell; if you've ever had NuGet packages where one package depends on library A at a particular version, and then another package depends on library A at a different version, then you'll know what I mean.

I'm still quite torn on the issue; nested hierarchy has the deficiency that you have to place a dependency at the most abstract level (i.e. you need to place MonoGame under the library and not at the top level).  At the same time, it means that if someone depends on your library module, they have everything they need to use the library.  But it also means you can't use two libraries both depending on MonoGame (well, you can, but I'm not sure what the results will end up like).  So I don't have a good answer as to what the ideal architecture is here.

Suggestions are welcome, but I'm pretty sure this is an area of build systems that doesn't have a perfect solution.

**Comment by emarcotte** [comment] 2015-02-03 22:34
I haven't spent much time with C#, I come from mostly java, so I'm mostly familiar with maven style dependencies (e.g. pulling compiled jars) and less so that of pulling source. Even then I have never really dug too deep into its internals.

I guess the main distinction would be that in this case we've got the code "in the project" vs an in external, compiled, shared copy (mavens ~/.m2 directory for example). When the project does it's dependency look up in maven it pulls the jars to that shared place and references them in the build proper.

Perhaps establishing a ~/.protobuild/ scheme or something for binary packages we could just reference a shared instance? Not sure honestly. It is still a bit wonky because I have ended up making a few tweaks to MonoGame so I really appreciate directly having the source available. 

In the case of version difference, I think maven users tend to mark an exclusion. Example: http://stackoverflow.com/questions/4827335/different-versions-of-the-same-dependency-in-maven. If the two different versions don't behave in a compatible way, I'm not sure how you could build the project successfully anyway. Which version would you ship with the final binary? And now we're back to API stability -- gosh things go deep fast!

Anyway, thanks for your thought on the subject, compared to what I thought was available for building C# projects on linux Protobuild is amazingly simple and effective. For now I'm dealing with it by just copying the project definition into the parent.

**Comment by hach-que** [comment] 2015-02-05 23:19
Yeah I've heard Maven handles dependency management a lot better than NuGet / what we're doing here.  The problem I've noticed is that .NET is much more strict about assembly versioning, which causes all kinds of craziness when using incompatible versions.

If Maven is pulling dependencies from a shared location (like ~/.m2), what happens when you modify the source code of that dependency?  Or do you have to explicitly tell Maven you want to fork the common dependency (and then how does that work when you push your changes to a Git repository, given the dependency is likely stored externally?)

**Comment by hach-que** [comment] 2015-02-06 12:25
I've done some work today which should potentially clear the way for having package dependencies sit outside their normal location (i.e. in a folder in the root module or in a common area).

**Comment by emarcotte** [comment] 2015-02-06 17:29
Typically with mavens you wouldn't have the source. The only times I have
is when using am IDE and having the source link for the debugger to use.

I've not had many occasions to make changes to the dependencies I user with
a mavens project though...

**Comment by hach-que** [comment] 2015-02-08 10:38
I almost have a solution implemented for this, so this feature is on it's way (it just needs some more testing first).

**Comment by hach-que** [comment] 2015-02-08 11:04
Okay, so with 3cc16d6 you should now be able to set this up in a reasonable manner.  Basically add the package at all levels of your hierarchy (add the MonoGame package to both your executable module and the library submodule).  When Protobuild runs it will automatically detect the multiple references to the same package, and ensure that only a single working copy of the package is created (at the highest level, so in this case inside the executable module).  The library projects will then reference the copy in the executable's module.

I'm about to do some testing on Windows to make sure everything works there.  If you run into bugs with this new functionality please let me know.

**Comment by hach-que** [comment] 2015-02-08 11:47
All the tests are passing for the new functionality, so I'm going to close this issue as resolved.

**Comment by emarcotte** [comment] 2015-02-08 12:45
Cool I'll give this a try this week!

**Comment by emarcotte** [comment] 2015-02-09 02:51
BTW this is working well for my use case on Linux & Windows. Thanks!

**Comment by emarcotte** [comment] 2015-02-09 03:49
Hrm, maybe I spoke to soon. A fresh checkout of my repository on Linux has this not working. Perhaps I didn't clean up properly the first time.

**Comment by hach-que** [comment] 2015-02-09 05:16
If you do "git clean -xdff" and then run Protobuild it should work, otherwise let me know.

**Comment by hach-que** [comment] 2015-02-09 10:11
I'll reopen this until we resolve any issues you might be having.

**Comment by emarcotte** [comment] 2015-02-09 22:57
On windows (VS2013) generation & compilation works fine. On linux, using xbuild, it reports that it can't find MonoGame.Framework in the submodule. Opening the generated csproj  I see some Reference tags. I commented those out and replaced with

    <ProjectReference Include="../relative/path/to/generated.csproj">
        <Project>{GUID HERE}</Project>
    </ProjectReference>

and xbuild seems to run to success now. I haven't tested with msbuild on windows to compare, but it seems like it might just be an xbuild difference from VS issue at this point.

**Comment by hach-que** [comment] 2015-02-09 22:58
Is there a ".redirect" file in the submodule's package folder?  Basically the library submodule should have a "MonoGame" folder (where the package was registered), and it should have a .redirect file whose contents is the path to the MonoGame folder in the executable module.

**Comment by emarcotte** [comment] 2015-02-10 00:33
The submodule doesn't have those. I'll try and package up a minimal
reproduction of the state of this thing.

**Comment by emarcotte** [comment] 2015-02-10 01:00
Here's a simple little App + 2 libs that seems to demonstrate the problem. Lib2 depends on Lib1 and App depends on both.

Before generation: 
https://dl.dropboxusercontent.com/u/282238/Dep.tar.bz2

After generation:
https://dl.dropboxusercontent.com/u/282238/Dep-generated.tar.bz2

If it matters:

````
Mono JIT compiler version 3.12.0 (tarball Thu Jan 15 08:07:24 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          yes(3.4svn-mono-/)
        GC:            sgen

[emarcotte@localhost Dep]$ cat /etc/redhat-release 
Fedora release 21 (Twenty One)
````

**Comment by hach-que** [comment] 2015-02-10 02:42
Oh, this change on a package basis; it uses package URIs to determine uniqueness of packages.

In the ZIP you've provided, you have nested submodules within (presumably) the same Git repository.  Protobuild submodules (and packages) tend to have a 1:1 relationship with Git repository URLs, that is, your submodules should either really be Git submodules (pointing to a different repository) or packages.

If you don't intend on cloning Lib1 or Lib2 independently from App, then you shouldn't put them in a separate submodule, just put them as projects in the same module.  Projects in this way will cross-reference as intended.

If you do want to clone or use Lib1 and Lib2 independently from App, you should store them in a seperate Git repository, and register the Git repository as a package on http://protobuild.org/ (you can also set up your own internal index using https://github.com/hach-que/Protobuild.Website).  Then you'd add the Lib1 and Lib2 packages to App, and add Lib1 as a package to Lib2.  When Protobuild resolves the packages it'll unify the working copies of Lib1 so that there's only one working copy of it in the module structure.

**Comment by emarcotte** [comment] 2015-02-10 02:45
My actual app uses submodules, didn't realize it was potentially breaking
for the test tho. Will retry spitting it out tomorrow with the small test
program. Thanks again!

**Comment by emarcotte** [comment] 2015-02-15 17:56
Sorry I didn't get back to this until now, but I still have trouble with actual submodules. (New archive: https://dl.dropboxusercontent.com/u/282238/Dep2.tar.bz2). Directory with 3 repos in it. Dep has submodule to the other 2 (lib1 lib2). Still results in 

```
xbuild /v:q /nologo /p:GenerateFullPaths=true "/p:Configuration=Debug" "/p:Platform=Any CPU"
/home/emarcotte/src/Dep2/Dep/Lib1/src/Lib1.cs(3,22): warning CS1591: Missing XML comment for publicly visible type or member `Lib1.Lib1'
/home/emarcotte/src/Dep2/Dep/Lib1/src/Lib1.cs(4,22): warning CS1591: Missing XML comment for publicly visible type or member `Lib1.Lib1.DoIt()'
/opt/mono/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Lib1' not resolved
/home/emarcotte/src/Dep2/Dep/Lib2/src/Lib2.cs(3,8): error CS0246: The type or namespace name `Lib1' could not be found. Are you missing an assembly reference?
Makefile:20: recipe for target 'compile' failed
make: *** [compile] Error 1
```

Setting up a package index for this seems like overkill, so I'd like to try and stick with submodules where possible.

**Comment by hach-que** [comment] 2015-02-16 00:59
The reason you're having trouble with submodules is because they're managed by Git, not Protobuild.  Thus the new uniqueness detection built into Protobuild doesn't kick in because it's not actually the process cloning the library source code.  When Git clones the submodules, it doesn't pay any attention as to whether there's already a copy of the submodule higher up or elsewhere in the module hierarchy.  

I just pushed a new version of Protobuild that allows you to add packages with `http-git://` and `https-git://` protocol URLs.  These URLs refer directly to the Git repositories that you want to add, and don't require a package index to be configured with a package.

For example, if you wanted to add a Git repository at https://github.com/emarcotte/Lib1, you would do `Protobuild.exe --add https-git://github.com/emarcotte/Lib1`.  This won't query any package indexes; it'll just treat it as if a package index returned with a result of "source package only at this Git URL; no binary versions available".

**Comment by emarcotte** [comment] 2015-02-16 02:05
Oh my mistake! I think I keep mixing up terminology. I will give this
version a try. Thanks again for all the help

**Comment by hach-que** [comment] 2015-02-16 02:14
Yeah there's a few different concepts here:

**Protobuild Module**: A module is a folder that has Protobuild.exe and Build\Module.xml.  When you have a Protobuild module inside another module (as a subdirectory), it's referred to as a submodule.

**Git Submodule**: These are submodules or "sub-repositories" managed by Git.  In the past before package management, Protobuild submodules had a one-to-one relationship with Git submodules.

**Protobuild Package**: This is the new, more preferred way of doing things.  These are very similar to Git submodules, but with additional metadata that allows Protobuild to be smarter about how Protobuild submodules exist.  This includes duplicate reference detection (where multiple Protobuild submodules use the same package, Protobuild will make sure there's only a single working copy), and support for binary / compiled versions of a package (which is entirely optional).  Both are supported when using a package managed by a package index (like the one on http://protobuild.org), but using the new `http-git://` / `https-git://` protocols, you can get the duplicate reference detection without registering a package anywhere.

**Comment by emarcotte** [comment] 2015-02-16 02:30
Looks like xbuild is happier. I've added https-git://url-to-lib/ and https-git://url-to-monogame/ in my main app and https-git://url-to-monogame/ in my lib as `<PackageRef>`s. Running Generate runs through the projects twice, but does only generate an "empty" MonoGame directory with a .redirect in the submodule.

Will play with it some and try to get the hang of it, but this issue can probably be closed -- until I do something else bone-headed again :)

**Comment by hach-que** [comment] 2015-02-16 02:31
> Looks like xbuild is happier. I've added https-git://url-to-lib/ and https-git://url-to-monogame/ in my main app and https-git://url-to-monogame/ in my lib as <PackageRef>s. Running Generate runs through the projects twice, but does only generate an "empty" MonoGame directory with a .redirect in the submodule.

That's the expected result :)

**Closed** 2015-02-16 02:30 UTC
